ecommerce/cart/urls.py
from django.urls import path
from cart import  views

app_name='cart'
urlpatterns = [
    path('addtocart/<int:i>',views.Addtocart.as_view(),name="addtocart"),
    path('cartview/',views.Cartview.as_view(),name="cartview"),
    path('reduce/<int:i>',views.reduce.as_view(),name="reduce"),
    path('delete/<int:i>', views.deletecart.as_view(), name="deletecart"),
    path('checkout/',views.Checkout.as_view(),name="checkout"),
    path('payment_success/<i>',views.Payment_success.as_view(),name="payment_success"),
    path('orders/',views.yourorders.as_view(),name="orders"),


]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('', include('cart.urls')),
    path('', include('search.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/search/urls.py
from django.urls import path
from search import  views
from django.conf import settings
from django.conf.urls.static import static
app_name='search'
urlpatterns = [
    path('search',views.Searchview.as_view(),name="search"),

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/shop/urls.py
from django.urls import path
from shop import  views
from django.conf import settings
from django.conf.urls.static import static
app_name='shop'
urlpatterns = [
    path('',views.Categoryview.as_view(),name="category"),
    path('productview/<int:i>',views.Productview.as_view(),name="products"),
    path('detail/<int:i>',views.Productdetail.as_view(),name="productdetail"),
    path('register/',views.Register.as_view(),name="register"),
    path('login/',views.Userlogin.as_view(),name="userlogin"),
    path('adminhome/',views.Adminhome.as_view(),name="adminhome"),
    path('logout/',views.Userlogout.as_view(),name="userlogout"),
    path('addcategory/',views.Addcategory.as_view(),name="addcategory"),
    path('addproduct/',views.Addproduct.as_view(),name="addproduct"),
    path('addstock/<int:i>',views.Addstock.as_view(),name="addstock"),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ecommerce/cart/models.py
from django.db import models
from shop.models import Product
from django.contrib.auth.models import User
# Create your models here.
class Cart(models.Model):
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField()
    date_added=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username

    def subtotal(self):
        return self.product.price*self.quantity


from django.utils import timezone
class Order(models.Model):
    amount=models.IntegerField(null=True)
    order_id=models.CharField(max_length=30,null=True)
    order_date=models.DateTimeField(auto_now=True)
    user=models.ForeignKey(User,on_delete=models.CASCADE)
    phone=models.IntegerField()
    address=models.TextField()
    is_ordered=models.BooleanField(default=False)
    payment_method=models.CharField(max_length=30)
    delivery_status=models.CharField(default="pending")
    def __str__(self):
        return self.user.username


class Order_items(models.Model):
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    order=models.ForeignKey(Order,on_delete=models.CASCADE,related_name="products")
    quantity=models.IntegerField()
    def __str__(self):
        return self.product.name

ecommerce/search/models.py
from django.db import models

# Create your models here.

ecommerce/cart/forms.py
from django import forms
from cart.models import Order
class Orderform(forms.ModelForm):
    payment_choices=[('cod','COD'),('online','ONLINE')]
    payment_method=forms.ChoiceField(choices=payment_choices)
    class Meta:
        model=Order
        fields=["address","phone","payment_method"]

ecommerce/cart/views.py
from django.shortcuts import render, redirect
from django.template.context_processors import request
from django.utils.decorators import method_decorator
from django.views import View
from pyexpat.errors import messages
from shop.models import Product
from cart.models import Cart
import uuid
import razorpay

from cart.models import Order_items


# Create your views here.
class Addtocart(View):
    def get(self,request,i):
        p=Product.objects.get(id=i)
        u=request.user
        try:
            c=Cart.objects.get(user=u,product=p) #check weather the product is added to the cart by the user
            c.quantity+=1 #if true increase the quantity
            c.save()
        except:
            c=Cart.objects.create(user=u,product=p,quantity=1)  #else create a new record in the cart table
            c.save()
        return redirect('cart:cartview')

class Cartview(View):
    def get(self,request):
        u=request.user
        c=Cart.objects.filter(user=u)
        total=0
        for i in c:
            total+=i.product.price * i.quantity
        context={'cart':c,'total':total}
        return render(request,'cart.html',context)



class reduce(View):
    def get(self,request,i):
        p=Product.objects.get(id=i)
        u=request.user
        try:
            c=Cart.objects.get(user=u,product=p)
            if c.quantity>1:
               c.quantity-=1
               c.save()
            else:
                c.delete()
        except:
            pass
        return redirect('cart:cartview')


class deletecart(View):
    def get(self,request,i):
        c=Cart.objects.get(id=i,user=request.user)
        c.delete()
        return redirect('cart:cartview')


#-----checkout---
from django.contrib import messages
from cart.forms import Orderform
def checkstock(c):
    for i in c:

        if i.quantity>i.product.stock:
           return  False
    else:
        return True

import random
class Checkout(View):
    def post(self,request):
        form_instance=Orderform(request.POST)
        if form_instance.is_valid():
            o=form_instance.save(commit=False)
            u=request.user
            o.user=u
            c=Cart.objects.filter(user=u)
            total=0
            for i in c:
                total+=i.product.price*i.quantity
            o.amount=total
            o.save()
            if(o.payment_method=="online"):
                # Razorpay client connection
                client=razorpay.Client(auth=('rzp_test_Re2KSWyKBOYNfG','fq6hlf1J3lQPzFXt5oPCV93F'))  #(auth=('key_id','key_secret'))
                print(client)
                #place order
                response_payment=client.order.create(dict(amount=total*100,currency='INR'))
                print(response_payment)
                id=response_payment['id']
                o.order_id=id
                o.save()
                context={'payment':response_payment}
                return render(request, 'payment.html',context)
            else:
                o.is_ordered = True  # after successful completion of order
                uid=uuid.uuid4().hex[:14]
                id='order_cod'+uid
                o.order_id=id
                o.save()


                # order_items

                order=Order.objects.get(order_id=id)
                for i in c:
                    o = Order_items.objects.create(order=order, product=i.product, quantity=i.quantity)
                    o.save()
                    o.product.stock -= o.quantity
                    o.product.save()

                    # delete
                c.delete()
                return render(request,'payment.html')



    def get(self,request):
        u=request.user
        c=Cart.objects.filter(user=u)
        stock=checkstock(c)
        if stock:
           form_instance=Orderform()
           context={'form':form_instance}
           return render(request,'checkout.html',context)
        else:
            messages.error(request,"Product is currently unavailable,please try again later")
            return  render(request,'checkout.html')

#payment success
from cart.models import Order
from django.contrib.auth import login
from django.contrib.auth.models import User
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
@method_decorator(csrf_exempt,name="dispatch")
class Payment_success(View):
    def post(self,request,i):# i represents the username ,to add user to the session again
        u=User.objects.get(username=i)
        login(request,u)
        response=request.POST #after successful payment razorpay send payment details back to the success view as response
        id=response['razorpay_order_id']
        print(id)

        #order
        order=Order.objects.get(order_id=id)
        order.is_ordered=True #after successful completion of order
        order.save()

        #order_items

        c=Cart.objects.filter(user=u)
        for i in c:
            o=Order_items.objects.create(order=order,product=i.product,quantity=i.quantity)
            o.save()
            o.product.stock-=o.quantity
            o.product.save()

            #delete
        c.delete()
        return render(request,'payment_success.html')




#---your orders
class yourorders(View):
    def get(self,request):
        u=request.user
        o=Order.objects.filter(user=u,is_ordered=True)
        context={'orders':o}
        return render(request,'orders.html',context)

ecommerce/search/views.py
from django.shortcuts import render
from django.views import  View
from shop.models import Product
from django.db.models import Q
# Create your views here.
class Searchview(View):
    def get(self,request):
        query=request.GET['q']
        if query:
            p=Product.objects.filter(Q(name__icontains=query)|Q(price__icontains=query)|Q(description__icontains=query))
            context={'product':p}
            return render(request,'search.html',context)

ecommerce/templates/addcategory.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Add category</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Add category</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

<!-----register form------>
<div class=" container mx-auto text-center mt-5 mb-5  pt-3 pb-3 bg-dark text-light rounded-3" style="border-radius:20px">
<form method="post" enctype="multipart/form-data" class="w-50 mx-auto">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="d-flex justify-content-center ">
        <input type="submit" class="btn bg-danger text-light mt-3 mb-3" value="Register">
    </div>
</form>
</div>
{% endblock %}

ecommerce/templates/addstock.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>ADDSTOCK</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Add stock</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

<!-----register form------>
<div class=" container mx-auto text-center mt-5 mb-5  pt-3 pb-3 bg-dark text-light rounded-3" style="border-radius:20px">
<form method="post" class="w-50 mx-auto">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="d-flex justify-content-center ">
        <input type="submit" class="btn bg-danger text-light mt-3 mb-3" value="Register">
    </div>
</form>
</div>
{% endblock %}

ecommerce/templates/adminhome.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">

                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Admin</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<div>
    <h1>admin home</h1>
</div>
{% endblock %}

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}



        <!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Cart</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active">Cart</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End All Title Box -->


    <!-- Start Cart  -->
    <div class="cart-box-main">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-main table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Image</th>
                                    <th>Product Name</th>
                                    <th>Price</th>
                                    <th>Quantity</th>
                                    <th>SubTotal</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                            {% for i in cart %}
                                <tr>
                                    <td class="thumbnail-img">
                                        <a href="#">
									<img class="img-fluid" src="{{ i.product.image.url }}" alt="" />
								</a>
                                    </td>
                                    <td class="name-pr">
                                        <a href="#">
									{{ i.product.name }}
								</a>
                                    </td>
                                    <td class="price-pr">
                                        <p>$ {{ i.product.price }}</p>
                                    </td>
                                    <td class="quantity-box"><p>{{ i.quantity }}</p></td>
                                    <td class="total-pr">
                                        <p>{{ i.subtotal }}</p>
                                    </td>
                                    <td class="remove-pr">
                                        {% if i.product.stock > 1 %}
                                           <a href="{% url 'cart:reduce' i.product.id %}">
									           <i class="fa-solid fa-minus"></i>
								           </a>

                                            <a href="{% url 'cart:addtocart' i.product.id%}">
									           <i class="fa-solid fa-plus"></i>
								            </a>
                                        
                                            <a href="{% url 'cart:deletecart' i.id %}">
									            <i class="fas fa-times"></i>
								             </a>
                                        {% else %}
                                            <a href="{% url 'cart:reduce' i.product.id %}">
									           <i class="fa-solid fa-minus"></i>
								            </a>

                                            <a href="{% url 'cart:deletecart' i.id %}">
									            <i class="fas fa-times"></i>
								            </a>
                                        {% endif %}
                                    </td>
                                </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>


            <div class="row my-5">
                <div class="col-lg-8 col-sm-12"></div>
                <div class="col-lg-4 col-sm-12">
                    <div class="order-box">
                        <h3>Order summary</h3>
                        <div class="d-flex">
                            <h4>Total</h4>
                            <div class="ml-auto font-weight-bold"> {{ total }} </div>
                        </div>

                        <hr class="my-1">

                        <div class="d-flex">
                            <h4>Shipping Cost</h4>
                            <div class="ml-auto font-weight-bold"> Free </div>
                        </div>
                        <hr>
                        <div class="d-flex gr-total">
                            <h5>Grand Total</h5>
                            <div class="ml-auto h5"> {{ total }} </div>
                        </div>
                        <hr> </div>
                </div>
                <div class="col-12 d-flex shopping-box"><a href="{% url 'cart:checkout' %}" class="ml-auto btn hvr-hover">Checkout</a> </div>
            </div>

        </div>
    </div>
    <!-- End Cart -->
{% endblock %}

ecommerce/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
 <!-- Start Slider -->
    <div id="slides-shop" class="cover-slides">
        <ul class="slides-container">
            <li class="text-center">
                <img src="{% static 'images/banner-01.jpg' %}" alt="">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="m-b-20"><strong>Welcome To <br> Freshshop</strong></h1>
                            <p class="m-b-40">See how your users experience your website in realtime or view <br> trends to see any changes in performance over time.</p>
                            <p><a class="btn hvr-hover " href="#"><b>Shop Now</b></a></p>
                        </div>
                    </div>
                </div>
            </li>
            <li class="text-center">
                <img src="{% static 'images/banner4.jpg' %}" alt="">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="m-b-20"><strong>Welcome To <br> Freshshop</strong></h1>
                            <p class="m-b-40">See how your users experience your website in realtime or view <br> trends to see any changes in performance over time.</p>
                            <p><a class="btn hvr-hover" href="#">Shop New</a></p>
                        </div>
                    </div>
                </div>
            </li>
            <li class="text-center">
                <img src="{% static 'images/banner5.jpg' %}" alt="">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="m-b-20"><strong>Welcome To <br> Freshshop</strong></h1>
                            <p class="m-b-40">See how your users experience your website in realtime or view <br> trends to see any changes in performance over time.</p>
                            <p><a class="btn hvr-hover" href="#">Shop New</a></p>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
        <div class="slides-navigation">
            <a href="#" class="next"><i class="fa fa-angle-right" aria-hidden="true"></i></a>
            <a href="#" class="prev"><i class="fa fa-angle-left" aria-hidden="true"></i></a>
        </div>
    </div>
    <!-- End Slider -->

 <div class="products-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="title-all text-center">
                        <h1>Our Collections</h1>
                        <p style="line-height:2">Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed sit amet lacus enim.Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. </p>
                    </div>
                </div>
            </div>
        </div>
 </div>
 <!-- Start Categories  -->
    <div class="categories-shop">
        <div class="container">
            <div class="row">
                {% for i in categories %}
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="shop-cat-box">
                        <img  src="{{ i.image.url }}" alt=""  height="300px" width="100%"/>
                        <a class="btn hvr-hover" href="{% url 'shop:products' i.id %}">{{ i.name }}</a>
<!--                        <p class="mt-2 text-center text-dark">{{ i.description }}</p>-->
                    </div>
                </div>

                {% endfor %}
            </div>
        </div>
    </div>
    <!-- End Categories -->
{% endblock %}

ecommerce/templates/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
  <!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Login</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Home</a></li>
                        <li class="breadcrumb-item active">Login</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>


<!----login form--->

<div class=" container mx-auto text-center mt-5 mb-5  pt-3 pb-3 bg-dark text-light rounded-3" style="border-radius:20px">
<form method="post" class="w-50 mx-auto">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="d-flex justify-content-center ">
        <input type="submit" class="btn bg-danger text-light mt-3 mb-3" value="LOGIN">
    </div>
</form>
</div>


{% if messages %}
<ul>
    {% for i in messages %}
    <li>{{ i }}</li>
    {% endfor %}
</ul>
{% endif %}
{% endblock %}

ecommerce/templates/orders.html
{% extends 'base.html' %}

{% block content %}



        <!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>orders</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active">orders</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

<h2 class="text-center">your orders </h2>

{% for i in orders %}
<div class="container mt-3 mb-3 shadow mb-3 mt-5">
    <strong>order id</strong>:{{ i.order_id }}<br>
    <strong>order date</strong>:{{ i.order_date }}<br>
    <strong>total amount</strong>:{{ i.amount }}<br>
    <hr style="border:1px solid black">
    <div class="card mb-3" style="max-width: 540px;">
        {% for j in i.products.all %}
   <div class="row g-0">
     <div class="col-md-4">
      <img src="{{ j.product.image.url }}" class="img-fluid rounded-start" alt="..." style="height:200px;width:200px">
     </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title"><strong>name</strong>:{{ j.product.name }}</h5>
        <p class="card-text"><strong>quantity</strong>:{{ j.product.quantity }}</p>
        <p class="card-text"><strong>price</strong>:{{ j.product.price }}</p>
      </div>
    </div>
  </div>
        {% endfor %}
 </div>
</div>
{% endfor %}


{% endblock %}

ecommerce/templates/ordersuccess.html
{% extends 'base.html' %}

{% block content %}



        <!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Payment</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active">Payment</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<h2>order successfull</h2>
{% endblock %}

ecommerce/templates/payment.html
{% extends 'base.html' %}

{% block content %}



        <!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Payment</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active">Payment</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

<div class="container mt-5 text-center p-5 w-50">
    {% if payment %}
<form action="{% url 'cart:payment_success' user.username %}" method="POST">
<script
   src="https://checkout.razorpay.com/v1/checkout.js"
    data-key="rzp_test_Re2KSWyKBOYNfG"
    data-amount="{{ payment.amount }}"
    data-currency="INR"
    data-order_id="{{ payment.id }}"
    data-buttontext="Pay with Razorpay"
    data-name="Acme Corp"
    data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
    data-image="https://example.com/your_logo.jpg"
    data-prefill.name="{{ user.username }}"
    data-prefill.email="{{ user.email }}"
    data-theme.color="#F37254"

></script>
<input type="hidden" custom="Hidden Element" name="hidden"/>
</form>
    {% else %}
    <h2>your order pl.aced successfully </h2>
    {% endif %}
</div>
{% endblock %}

ecommerce/templates/payment_success.html
{% extends 'base.html' %}

{% block content %}



        <!-- Start All Title Box -->
    <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Payment</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active">Payment</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
<h2>payment successfull</h2>
{% endblock %}

ecommerce/templates/productview.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

 <div class="products-box">
     <div class="container-fluid">
         <img src="{{ category.image.url }}" height="300px" width="100%">
     </div>
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="title-all text-center">
                        <h1>{{ category.name }}</h1>
                        <p>{{ category.description }}</p>
                    </div>
                </div>
            </div>


            <div class="row special-list">
                {% for i in category.products.all %}
                <div class="col-lg-3 col-md-6 special-grid best-seller">
                    <div class="products-single fix">
                        <div class="box-img-hover">
                            <div class="type-lb">
                                <p class="sale">Sale</p>
                            </div>
                            <img src="{{ i.image.url }}" class="img-fluid" alt="Image" style="height:200px;width:100%">
                            <div class="mask-icon">
                                <ul>
                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="View"><i class="fas fa-eye"></i></a></li>
                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="Compare"><i class="fas fa-sync-alt"></i></a></li>
                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="Add to Wishlist"><i class="far fa-heart"></i></a></li>
                                </ul>
                                <a class="cart" href="{% url 'shop:productdetail' i.id %}">Detail</a>
                            </div>
                        </div>
                        <div class="why-text">
                            <h4>{{ i.name }}</h4>
                            <h5> ${{ i.price }}</h5>
                        </div>
                    </div>
                </div>{% endfor %}
            </div>

                {% endblock %}

ecommerce/templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
 <h2 class="text-center mt-3">SEARCH RESULTS</h2>
<div class="products-box">

        <div class="container">


            {% if product %}
            <div class="row special-list">
             {% for i in product %}
                <div class="col-lg-3 col-md-6 special-grid best-seller">
                    <div class="products-single fix">
                        <div class="box-img-hover">
                            <div class="type-lb">
                                <p class="sale">Sale</p>
                            </div>
                            <img src="{{ i.image.url }}" class="img-fluid" alt="Image" style="height:200px;width:100%">
                            <div class="mask-icon">
                                <ul>
                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="View"><i class="fas fa-eye"></i></a></li>
                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="Compare"><i class="fas fa-sync-alt"></i></a></li>
                                    <li><a href="#" data-toggle="tooltip" data-placement="right" title="Add to Wishlist"><i class="far fa-heart"></i></a></li>
                                </ul>
                                <a class="cart" href="{% url 'shop:productdetail' i.id %}">Detail</a>
                            </div>
                        </div>
                        <div class="why-text">
                            <h4>{{ i.name }}</h4>
                            <h5> ${{ i.price }}</h5>
                        </div>
                    </div>
                </div>{% endfor %}
               {% else %}
         <h2 class="text-danger text-center mt-5 mb-5"> No Results found</h2>
         {% endif %}
            </div>

{% endblock %}